"""Create agentic tutor conversations, tool audit and visual tasks."""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "agent_thread",
        sa.Column(
            "agent_thread_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "student_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "student_learning_context_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "student_subject_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "student_learning_unit_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "title",
            sa.String(length=250),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="ACTIVE",
        ),
        sa.Column(
            "memory_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "last_message_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','ARCHIVED')",
            name="ck_agent_thread_status",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["lia2.student.student_id"],
            name="fk_agent_thread_student",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_learning_context_id"],
            [
                "lia2.student_learning_context."
                "student_learning_context_id"
            ],
            name="fk_agent_thread_context",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_subject_id"],
            ["lia2.student_subject.student_subject_id"],
            name="fk_agent_thread_subject",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_learning_unit_id"],
            [
                "lia2.student_learning_unit."
                "student_learning_unit_id"
            ],
            name="fk_agent_thread_unit",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "agent_thread_id",
            name="pk_agent_thread",
        ),
        schema="lia2",
    )
    op.create_index(
        "ix_agent_thread_student_updated",
        "agent_thread",
        ["student_id", "updated_at"],
        schema="lia2",
    )

    op.create_table(
        "agent_message",
        sa.Column(
            "agent_message_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "agent_thread_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "citations_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "visual_task_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "actions_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "role IN ('USER','ASSISTANT')",
            name="ck_agent_message_role",
        ),
        sa.ForeignKeyConstraint(
            ["agent_thread_id"],
            ["lia2.agent_thread.agent_thread_id"],
            name="fk_agent_message_thread",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "agent_message_id",
            name="pk_agent_message",
        ),
        schema="lia2",
    )
    op.create_index(
        "ix_agent_message_thread_created",
        "agent_message",
        ["agent_thread_id", "created_at"],
        schema="lia2",
    )

    op.create_table(
        "agent_run",
        sa.Column(
            "agent_run_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "agent_thread_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "user_message_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "assistant_message_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="QUEUED",
        ),
        sa.Column(
            "stage",
            sa.String(length=40),
            nullable=False,
            server_default="QUEUED",
        ),
        sa.Column(
            "progress_percent",
            sa.Integer(),
            nullable=False,
            server_default="5",
        ),
        sa.Column(
            "message",
            sa.String(length=500),
            nullable=False,
            server_default="Na fila para a Lia.",
        ),
        sa.Column(
            "requested_text_model_id",
            sa.String(length=300),
            nullable=True,
        ),
        sa.Column(
            "effective_text_model_id",
            sa.String(length=300),
            nullable=True,
        ),
        sa.Column(
            "thinking_mode",
            sa.String(length=10),
            nullable=False,
            server_default="AUTO",
        ),
        sa.Column(
            "effective_thinking_enabled",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "plan_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "error_code",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "error_message",
            sa.String(length=1000),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED','RUNNING','READY','FAILED','CANCELLED')",
            name="ck_agent_run_status",
        ),
        sa.CheckConstraint(
            "thinking_mode IN ('AUTO','ON','OFF')",
            name="ck_agent_run_thinking_mode",
        ),
        sa.CheckConstraint(
            "progress_percent BETWEEN 0 AND 100",
            name="ck_agent_run_progress",
        ),
        sa.ForeignKeyConstraint(
            ["agent_thread_id"],
            ["lia2.agent_thread.agent_thread_id"],
            name="fk_agent_run_thread",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_message_id"],
            ["lia2.agent_message.agent_message_id"],
            name="fk_agent_run_user_message",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["assistant_message_id"],
            ["lia2.agent_message.agent_message_id"],
            name="fk_agent_run_assistant_message",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "agent_run_id",
            name="pk_agent_run",
        ),
        schema="lia2",
    )
    op.create_index(
        "ix_agent_run_status_created",
        "agent_run",
        ["status", "created_at"],
        schema="lia2",
    )

    op.create_table(
        "agent_tool_call",
        sa.Column(
            "agent_tool_call_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "agent_run_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "tool_name",
            sa.String(length=80),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="STARTED",
        ),
        sa.Column(
            "request_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column(
            "response_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            "error_code",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "error_message",
            sa.String(length=1000),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.CheckConstraint(
            "status IN ('STARTED','COMPLETED','FAILED')",
            name="ck_agent_tool_call_status",
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["lia2.agent_run.agent_run_id"],
            name="fk_agent_tool_call_run",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "agent_tool_call_id",
            name="pk_agent_tool_call",
        ),
        schema="lia2",
    )
    op.create_index(
        "ix_agent_tool_call_run_started",
        "agent_tool_call",
        ["agent_run_id", "started_at"],
        schema="lia2",
    )

    op.create_table(
        "visual_task",
        sa.Column(
            "visual_task_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "student_id",
            postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "agent_thread_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "agent_run_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "pedagogical_artifact_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "visual_type",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="READY",
        ),
        sa.Column(
            "title",
            sa.String(length=250),
            nullable=False,
        ),
        sa.Column(
            "renderer",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "spec_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "evidence_json",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "source_material_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column(
            "effective_model_id",
            sa.String(length=300),
            nullable=True,
        ),
        sa.Column(
            "thinking_enabled",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "visual_type IN ("
            "'MIND_MAP','DIAGRAM','CHART','ANIMATION_2D','SCENE_3D'"
            ")",
            name="ck_visual_task_type",
        ),
        sa.CheckConstraint(
            "renderer IN ('SVG','CANVAS','THREE')",
            name="ck_visual_task_renderer",
        ),
        sa.CheckConstraint(
            "status IN ('READY','ARCHIVED')",
            name="ck_visual_task_status",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["lia2.student.student_id"],
            name="fk_visual_task_student",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["agent_thread_id"],
            ["lia2.agent_thread.agent_thread_id"],
            name="fk_visual_task_thread",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["agent_run_id"],
            ["lia2.agent_run.agent_run_id"],
            name="fk_visual_task_run",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["pedagogical_artifact_id"],
            [
                "lia2.pedagogical_artifact."
                "pedagogical_artifact_id"
            ],
            name="fk_visual_task_artifact",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "visual_task_id",
            name="pk_visual_task",
        ),
        schema="lia2",
    )
    op.create_index(
        "ix_visual_task_student_created",
        "visual_task",
        ["student_id", "created_at"],
        schema="lia2",
    )


def downgrade() -> None:
    op.drop_index(
        "ix_visual_task_student_created",
        table_name="visual_task",
        schema="lia2",
    )
    op.drop_table("visual_task", schema="lia2")

    op.drop_index(
        "ix_agent_tool_call_run_started",
        table_name="agent_tool_call",
        schema="lia2",
    )
    op.drop_table("agent_tool_call", schema="lia2")

    op.drop_index(
        "ix_agent_run_status_created",
        table_name="agent_run",
        schema="lia2",
    )
    op.drop_table("agent_run", schema="lia2")

    op.drop_index(
        "ix_agent_message_thread_created",
        table_name="agent_message",
        schema="lia2",
    )
    op.drop_table("agent_message", schema="lia2")

    op.drop_index(
        "ix_agent_thread_student_updated",
        table_name="agent_thread",
        schema="lia2",
    )
    op.drop_table("agent_thread", schema="lia2")
